FROM quay.io/toolbx-images/debian-toolbox:11

RUN sudo apt-get update && sudo apt-get -y install git-flow curl jq python-is-python3 python3-distutils
RUN curl -fsSL 'https://azurecliprod.blob.core.windows.net/$root/deb_install.sh' | sudo bash
RUN az devops configure --defaults organization=https://dev.azure.com/indinl project=General\ projects
