ARG VERSION=42
FROM quay.io/jometzner/toolbox-base:${VERSION}

RUN curl -o resilio-sync.tar.gz -L "https://download-cdn.resilio.com/stable/linux/x64/0/resilio-sync_x64.tar.gz" && \
    tar -xvzf resilio-sync.tar.gz -C /usr/local/bin rslsync && \
    rm resilio-sync.tar.gz
