FROM quay.io/jometzner/toolbox-base:42

RUN rpm --import https://linux-packages.resilio.com/resilio-sync/key.asc
RUN printf "[resilio-sync]\nname=Resilio Sync\nbaseurl=https://linux-packages.resilio.com/resilio-sync/rpm/\$basearch\nenabled=1\ngpgcheck=1\n" | {{ $sudo }}tee /etc/yum.repos.d/resilio-sync.repo
RUN dnf -y update && \
    dnf -y install resilio-sync && \
    dnf clean all