name: CI (main)
# This workflow is triggered on pushes to main and runs tests and performs the release steps

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    name: "Build and test"
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v2
        with:
          token: "${{secrets.COMMIT_SECRET}}"
      - name: Build and run dev container task
        uses: devcontainers/ci@v0.2
        with:
          runCmd: |
            mkdir ~/.ssh
            echo "github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl" > ~/.ssh/known_hosts
            chezmoi init /workspaces/dotfiles