name: CI (main)
# This workflow is triggered on pushes to main and runs tests and performs the release steps

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    name: "Build and test"
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3
      - name: Build and run dev container task
        uses: devcontainers/ci@v0.3
        with:
          push: never
          runCmd: |
            mkdir ~/.ssh
            ssh-keyscan github.com > ~/.ssh/known_hosts
            chezmoi init /workspaces/dotfiles/ --recurse-submodules=false --promptString="Used Email=test@test"
